//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Replica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Replica() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("replica.sl.globalization.Replica", typeof(Replica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string sAutumn {
            get {
                return ResourceManager.GetString("sAutumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check minimum.
        /// </summary>
        public static string sBtnCheckMinimum {
            get {
                return ResourceManager.GetString("sBtnCheckMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string sCampaign {
            get {
                return ResourceManager.GetString("sCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string sCompany {
            get {
                return ResourceManager.GetString("sCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown video type.
        /// </summary>
        public static string sErrorAssetProperties1 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while program account save.
        /// </summary>
        public static string sErrorAssetProperties2 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors occurred while frequency of assets words occurrences get.
        /// </summary>
        public static string sErrorAssetProperties3 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cues classes information missing.
        /// </summary>
        public static string sErrorAssetProperties4 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while program cues markers save.
        /// </summary>
        public static string sErrorAssetProperties5 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset account save was successful, but errors occurred while playlist update.
        /// </summary>
        public static string sErrorAssetProperties6 {
            get {
                return ResourceManager.GetString("sErrorAssetProperties6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parents of these assets have been removed or not found, try to set them the new parents! They will be at the root level of the list and highlighted in red..
        /// </summary>
        public static string sErrorAssetsList1 {
            get {
                return ResourceManager.GetString("sErrorAssetsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot determine the active tab.
        /// </summary>
        public static string sErrorAssetsList2 {
            get {
                return ResourceManager.GetString("sErrorAssetsList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors occurred while asset delete.
        /// </summary>
        public static string sErrorAssetsList3 {
            get {
                return ResourceManager.GetString("sErrorAssetsList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors occurred while assets update!.
        /// </summary>
        public static string sErrorAssetsList4 {
            get {
                return ResourceManager.GetString("sErrorAssetsList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while assets parent set!.
        /// </summary>
        public static string sErrorAssetsList6 {
            get {
                return ResourceManager.GetString("sErrorAssetsList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete Assets (eg, {1}),{0}which still have children (eg, {2}){0}{0}First unset parents or delete them..
        /// </summary>
        public static string sErrorAssetsList8 {
            get {
                return ResourceManager.GetString("sErrorAssetsList8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unset parents from these assets?.
        /// </summary>
        public static string sErrorAssetsList9 {
            get {
                return ResourceManager.GetString("sErrorAssetsList9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving classes was unsuccessful on these assets:.
        /// </summary>
        public static string sErrorAssetsProperties1 {
            get {
                return ResourceManager.GetString("sErrorAssetsProperties1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving rotations was unsuccessful on these assets:.
        /// </summary>
        public static string sErrorAssetsProperties2 {
            get {
                return ResourceManager.GetString("sErrorAssetsProperties2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get important information from DB about the transliteration/nProbably due to permissions problems.
        /// </summary>
        public static string sErrorIngest1 {
            get {
                return ResourceManager.GetString("sErrorIngest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a folder, a storage, a type and a name for a new tab.
        /// </summary>
        public static string sErrorIngest2 {
            get {
                return ResourceManager.GetString("sErrorIngest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename differs from the target and will not be used! Do you want to continue?.
        /// </summary>
        public static string sErrorIngest3 {
            get {
                return ResourceManager.GetString("sErrorIngest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify {0}!!.
        /// </summary>
        public static string sErrorIngest4 {
            get {
                return ResourceManager.GetString("sErrorIngest4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The replaceable file is likely already cached, or in the process! {0} It is not recommended to replace it right now! {0} Continue only if you REALLY can control all the consequences!!.
        /// </summary>
        public static string sErrorIngest5 {
            get {
                return ResourceManager.GetString("sErrorIngest5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither the original nor current file names does not match Your filename!!{0}Are You SURE????{0}Possibly the wrong file will pass to the air!!.
        /// </summary>
        public static string sErrorIngest6 {
            get {
                return ResourceManager.GetString("sErrorIngest6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete these artists.
        /// </summary>
        public static string sErrorPersonsList1 {
            get {
                return ResourceManager.GetString("sErrorPersonsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to continue! Adding to playlist already in process, maybe you are copying a part of the playlist.
        /// </summary>
        public static string sErrorPlaylist1 {
            get {
                return ResourceManager.GetString("sErrorPlaylist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status must be &apos;planned&apos;.
        /// </summary>
        public static string sErrorPlaylist10 {
            get {
                return ResourceManager.GetString("sErrorPlaylist10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status must not be &apos;onair&apos; to delete element.
        /// </summary>
        public static string sErrorPlaylist11 {
            get {
                return ResourceManager.GetString("sErrorPlaylist11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding task went with errors.
        /// </summary>
        public static string sErrorPlaylist12 {
            get {
                return ResourceManager.GetString("sErrorPlaylist12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! The total recalculation is needed!.
        /// </summary>
        public static string sErrorPlaylist13 {
            get {
                return ResourceManager.GetString("sErrorPlaylist13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculation is impossible.
        /// </summary>
        public static string sErrorPlaylist2 {
            get {
                return ResourceManager.GetString("sErrorPlaylist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to continue! Adding to playlist already in process, maybe you pressed &apos;Import&apos;.
        /// </summary>
        public static string sErrorPlaylist3 {
            get {
                return ResourceManager.GetString("sErrorPlaylist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while recalculation.
        /// </summary>
        public static string sErrorPlaylist4 {
            get {
                return ResourceManager.GetString("sErrorPlaylist4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! The target range already has planned items!{0}Remove them first!.
        /// </summary>
        public static string sErrorPlaylist6 {
            get {
                return ResourceManager.GetString("sErrorPlaylist6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Error occurred while item start time update!.
        /// </summary>
        public static string sErrorPlaylist7 {
            get {
                return ResourceManager.GetString("sErrorPlaylist7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deleting range has cached items. Try to refresh the playlist..
        /// </summary>
        public static string sErrorPlaylist8 {
            get {
                return ResourceManager.GetString("sErrorPlaylist8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some items ({0}) were not deleted!.
        /// </summary>
        public static string sErrorPlaylist9 {
            get {
                return ResourceManager.GetString("sErrorPlaylist9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot find one or more specified files.
        /// </summary>
        public static string sErrorPlaylistImport1 {
            get {
                return ResourceManager.GetString("sErrorPlaylistImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for timecodes loading....
        /// </summary>
        public static string sErrorRecalculate2 {
            get {
                return ResourceManager.GetString("sErrorRecalculate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load timecodes first....
        /// </summary>
        public static string sErrorRecalculate3 {
            get {
                return ResourceManager.GetString("sErrorRecalculate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;played&apos; status was not found!.
        /// </summary>
        public static string sErrorStat1 {
            get {
                return ResourceManager.GetString("sErrorStat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get information about cues.tTemplate.
        /// </summary>
        public static string sErrorTemplates1 {
            get {
                return ResourceManager.GetString("sErrorTemplates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add changes..
        /// </summary>
        public static string sErrorTemplates2 {
            get {
                return ResourceManager.GetString("sErrorTemplates2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps some templates have not been saved!{0}Leave the page and return to it again to update and verify the contents..
        /// </summary>
        public static string sErrorTemplates3 {
            get {
                return ResourceManager.GetString("sErrorTemplates3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add because another trailer scheduled at this time already.
        /// </summary>
        public static string sErrorTemplates4 {
            get {
                return ResourceManager.GetString("sErrorTemplates4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file (not copy).
        /// </summary>
        public static string sMoveFile {
            get {
                return ResourceManager.GetString("sMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create an asset.
        /// </summary>
        public static string sNoAsset {
            get {
                return ResourceManager.GetString("sNoAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist : Song.
        /// </summary>
        public static string sNoticeArtistSearch1 {
            get {
                return ResourceManager.GetString("sNoticeArtistSearch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as block:.
        /// </summary>
        public static string sNoticeAssetChooser1 {
            get {
                return ResourceManager.GetString("sNoticeAssetChooser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add assets to the sequence.
        /// </summary>
        public static string sNoticeAssetChooser2 {
            get {
                return ResourceManager.GetString("sNoticeAssetChooser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected:.
        /// </summary>
        public static string sNoticeAssetChooser3 {
            get {
                return ResourceManager.GetString("sNoticeAssetChooser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ASSETS SELECTED.
        /// </summary>
        public static string sNoticeAssetChooser4 {
            get {
                return ResourceManager.GetString("sNoticeAssetChooser4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a name from the cues.     (CTRL + M).
        /// </summary>
        public static string sNoticeAssetProperties1 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make changes to playlist.
        /// </summary>
        public static string sNoticeAssetProperties2 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clip timings.
        /// </summary>
        public static string sNoticeAssetProperties3 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fragment timings.
        /// </summary>
        public static string sNoticeAssetProperties4 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat in/out markers.
        /// </summary>
        public static string sNoticeAssetProperties5 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove ALL markers.
        /// </summary>
        public static string sNoticeAssetProperties6 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset last show:.
        /// </summary>
        public static string sNoticeAssetProperties7 {
            get {
                return ResourceManager.GetString("sNoticeAssetProperties7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh     (F9).
        /// </summary>
        public static string sNoticeAssetsList1 {
            get {
                return ResourceManager.GetString("sNoticeAssetsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first item start type.
        /// </summary>
        public static string sNoticeGroupMoving1 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first item show time.
        /// </summary>
        public static string sNoticeGroupMoving2 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned start.
        /// </summary>
        public static string sNoticeGroupMoving3 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start was.
        /// </summary>
        public static string sNoticeGroupMoving4 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type was.
        /// </summary>
        public static string sNoticeGroupMoving5 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start will be.
        /// </summary>
        public static string sNoticeGroupMoving6 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type will be.
        /// </summary>
        public static string sNoticeGroupMoving7 {
            get {
                return ResourceManager.GetString("sNoticeGroupMoving7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source file:.
        /// </summary>
        public static string sNoticeIngest1 {
            get {
                return ResourceManager.GetString("sNoticeIngest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path (local).
        /// </summary>
        public static string sNoticeIngest10 {
            get {
                return ResourceManager.GetString("sNoticeIngest10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad.
        /// </summary>
        public static string sNoticeIngest11 {
            get {
                return ResourceManager.GetString("sNoticeIngest11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast.
        /// </summary>
        public static string sNoticeIngest12 {
            get {
                return ResourceManager.GetString("sNoticeIngest12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best.
        /// </summary>
        public static string sNoticeIngest13 {
            get {
                return ResourceManager.GetString("sNoticeIngest13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to season.
        /// </summary>
        public static string sNoticeIngest14 {
            get {
                return ResourceManager.GetString("sNoticeIngest14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to proceed - the list is empty.
        /// </summary>
        public static string sNoticeIngest15 {
            get {
                return ResourceManager.GetString("sNoticeIngest15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show:.
        /// </summary>
        public static string sNoticeIngest2 {
            get {
                return ResourceManager.GetString("sNoticeIngest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ready for broadcast:.
        /// </summary>
        public static string sNoticeIngest3 {
            get {
                return ResourceManager.GetString("sNoticeIngest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreign language:.
        /// </summary>
        public static string sNoticeIngest4 {
            get {
                return ResourceManager.GetString("sNoticeIngest4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target file path:.
        /// </summary>
        public static string sNoticeIngest5 {
            get {
                return ResourceManager.GetString("sNoticeIngest5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to life time (monthes, 0 = forever):.
        /// </summary>
        public static string sNoticeIngest6 {
            get {
                return ResourceManager.GetString("sNoticeIngest6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiration action:.
        /// </summary>
        public static string sNoticeIngest7 {
            get {
                return ResourceManager.GetString("sNoticeIngest7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commercial.
        /// </summary>
        public static string sNoticeIngest8 {
            get {
                return ResourceManager.GetString("sNoticeIngest8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage.
        /// </summary>
        public static string sNoticeIngest9 {
            get {
                return ResourceManager.GetString("sNoticeIngest9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press:  &apos;ESC&apos; - Cancel,   &apos;ENTER&apos; - OK.
        /// </summary>
        public static string sNoticeMedia1 {
            get {
                return ResourceManager.GetString("sNoticeMedia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   show not more than .
        /// </summary>
        public static string sNoticeMediaList1 {
            get {
                return ResourceManager.GetString("sNoticeMediaList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items    .
        /// </summary>
        public static string sNoticeMediaList2 {
            get {
                return ResourceManager.GetString("sNoticeMediaList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate full playlist.
        /// </summary>
        public static string sNoticePlaylist1 {
            get {
                return ResourceManager.GetString("sNoticePlaylist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time.
        /// </summary>
        public static string sNoticePlaylist10 {
            get {
                return ResourceManager.GetString("sNoticePlaylist10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came to cMsgDate_Closed .
        /// </summary>
        public static string sNoticePlaylist11 {
            get {
                return ResourceManager.GetString("sNoticePlaylist11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how many times to copy the selection to the end of the playlist.{0}A sequence of all items will be preserved,{0}but the structure of the blocks WILL BE LOST!.
        /// </summary>
        public static string sNoticePlaylist12 {
            get {
                return ResourceManager.GetString("sNoticePlaylist12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the exact start time from which items will be placed.{0}In the copy target range, playlist should not have any other items!{0}Before copying there will be a corresponding check,{0}however it may fail in a case if the playlist has not been recalculated{0}{0}As a result of copying the structure of the blocks will be preserved while all plugs will be removed.{0}.
        /// </summary>
        public static string sNoticePlaylist13 {
            get {
                return ResourceManager.GetString("sNoticePlaylist13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to refresh the playlist.
        /// </summary>
        public static string sNoticePlaylist14 {
            get {
                return ResourceManager.GetString("sNoticePlaylist14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came to _cDBI_PlaylistItemStartsSetCompleted.
        /// </summary>
        public static string sNoticePlaylist15 {
            get {
                return ResourceManager.GetString("sNoticePlaylist15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move was successful!{0}{0}To see the results, run a partial or a full recalculation of the playlist..
        /// </summary>
        public static string sNoticePlaylist16 {
            get {
                return ResourceManager.GetString("sNoticePlaylist16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on air:.
        /// </summary>
        public static string sNoticePlaylist17 {
            get {
                return ResourceManager.GetString("sNoticePlaylist17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate the playlist for {0} {1} starting from &quot;{2}&quot;?.
        /// </summary>
        public static string sNoticePlaylist2 {
            get {
                return ResourceManager.GetString("sNoticePlaylist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy selected to the time....
        /// </summary>
        public static string sNoticePlaylist20 {
            get {
                return ResourceManager.GetString("sNoticePlaylist20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcast date and time.
        /// </summary>
        public static string sNoticePlaylist21 {
            get {
                return ResourceManager.GetString("sNoticePlaylist21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to another time.
        /// </summary>
        public static string sNoticePlaylist22 {
            get {
                return ResourceManager.GetString("sNoticePlaylist22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert assets after or add a block....
        /// </summary>
        public static string sNoticePlaylist23 {
            get {
                return ResourceManager.GetString("sNoticePlaylist23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete ALL starting from.
        /// </summary>
        public static string sNoticePlaylist24 {
            get {
                return ResourceManager.GetString("sNoticePlaylist24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recalculate next 5 hours.
        /// </summary>
        public static string sNoticePlaylist25 {
            get {
                return ResourceManager.GetString("sNoticePlaylist25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy selected to the end....
        /// </summary>
        public static string sNoticePlaylist26 {
            get {
                return ResourceManager.GetString("sNoticePlaylist26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string sNoticePlaylist27 {
            get {
                return ResourceManager.GetString("sNoticePlaylist27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string sNoticePlaylist28 {
            get {
                return ResourceManager.GetString("sNoticePlaylist28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned.
        /// </summary>
        public static string sNoticePlaylist29 {
            get {
                return ResourceManager.GetString("sNoticePlaylist29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ONE playlist item after which you want to insert asset(s).
        /// </summary>
        public static string sNoticePlaylist3 {
            get {
                return ResourceManager.GetString("sNoticePlaylist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        public static string sNoticePlaylist30 {
            get {
                return ResourceManager.GetString("sNoticePlaylist30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduling of advanced playlist....
        /// </summary>
        public static string sNoticePlaylist31 {
            get {
                return ResourceManager.GetString("sNoticePlaylist31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date and time.
        /// </summary>
        public static string sNoticePlaylist32 {
            get {
                return ResourceManager.GetString("sNoticePlaylist32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the new playlist.
        /// </summary>
        public static string sNoticePlaylist33 {
            get {
                return ResourceManager.GetString("sNoticePlaylist33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task  added.
        /// </summary>
        public static string sNoticePlaylist34 {
            get {
                return ResourceManager.GetString("sNoticePlaylist34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you SURE you want to start this playlist OVER THE MAIN AIR ??????.
        /// </summary>
        public static string sNoticePlaylist35 {
            get {
                return ResourceManager.GetString("sNoticePlaylist35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s impossible to insert item after just inserted (and not recalculated) item.
        /// </summary>
        public static string sNoticePlaylist36 {
            get {
                return ResourceManager.GetString("sNoticePlaylist36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not attach items to not yet added or cached item.
        /// </summary>
        public static string sNoticePlaylist4 {
            get {
                return ResourceManager.GetString("sNoticePlaylist4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groop moving.
        /// </summary>
        public static string sNoticePlaylist5 {
            get {
                return ResourceManager.GetString("sNoticePlaylist5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you SURE you want to remove more than 10 playlist items???.
        /// </summary>
        public static string sNoticePlaylist6 {
            get {
                return ResourceManager.GetString("sNoticePlaylist6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you SURE you want to remove ALL playlist items starting from.
        /// </summary>
        public static string sNoticePlaylist7 {
            get {
                return ResourceManager.GetString("sNoticePlaylist7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came to _ui_cmPlanned_Move.
        /// </summary>
        public static string sNoticePlaylist8 {
            get {
                return ResourceManager.GetString("sNoticePlaylist8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new broadcast time bellow:.
        /// </summary>
        public static string sNoticePlaylist9 {
            get {
                return ResourceManager.GetString("sNoticePlaylist9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clips file:.
        /// </summary>
        public static string sNoticePlaylistImport1 {
            get {
                return ResourceManager.GetString("sNoticePlaylistImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advertisement file:.
        /// </summary>
        public static string sNoticePlaylistImport2 {
            get {
                return ResourceManager.GetString("sNoticePlaylistImport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binding date:.
        /// </summary>
        public static string sNoticePlaylistImport3 {
            get {
                return ResourceManager.GetString("sNoticePlaylistImport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design file:.
        /// </summary>
        public static string sNoticePlaylistImport4 {
            get {
                return ResourceManager.GetString("sNoticePlaylistImport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge playlists.
        /// </summary>
        public static string sNoticePlaylistImport5 {
            get {
                return ResourceManager.GetString("sNoticePlaylistImport5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        public static string sNoticeStat1 {
            get {
                return ResourceManager.GetString("sNoticeStat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png-sequence folder name.
        /// </summary>
        public static string sNoticeTemplates1 {
            get {
                return ResourceManager.GetString("sNoticeTemplates1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press digits, enter or escape.
        /// </summary>
        public static string sNoticeTimeCodeEnter1 {
            get {
                return ResourceManager.GetString("sNoticeTimeCodeEnter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to advertisement.
        /// </summary>
        public static string sPathAdvertisement {
            get {
                return ResourceManager.GetString("sPathAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to trailers.
        /// </summary>
        public static string sPathTrailers {
            get {
                return ResourceManager.GetString("sPathTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace selected file.
        /// </summary>
        public static string sReplaceSelectedFile {
            get {
                return ResourceManager.GetString("sReplaceSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string sSpring {
            get {
                return ResourceManager.GetString("sSpring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements storage.
        /// </summary>
        public static string sStorageAdvertisement {
            get {
                return ResourceManager.GetString("sStorageAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers storage.
        /// </summary>
        public static string sStorageTrailers {
            get {
                return ResourceManager.GetString("sStorageTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string sSummer {
            get {
                return ResourceManager.GetString("sSummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file with the same name has already been uploaded earlier! Are you sure you want to replace it?.
        /// </summary>
        public static string sWarningIngest1 {
            get {
                return ResourceManager.GetString("sWarningIngest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such binding code is already in the Asset:{0}{1}{0}with file:{2}{0}{0}.
        /// </summary>
        public static string sWarningIngest2 {
            get {
                return ResourceManager.GetString("sWarningIngest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The replaceable file is in the on-air playlist!{0}It is necessary to discuss the replacement with your media planner!.
        /// </summary>
        public static string sWarningIngest3 {
            get {
                return ResourceManager.GetString("sWarningIngest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in merged playlist!{0}It&apos;s strongly recommended to stop import!{0}Are You sure that You can control all the consequences???.
        /// </summary>
        public static string sWarningPlaylistImport1 {
            get {
                return ResourceManager.GetString("sWarningPlaylistImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string sWinter {
            get {
                return ResourceManager.GetString("sWinter", resourceCulture);
            }
        }
    }
}
