----------------------------------- ia."tMessages"
----------------------------------- ia."tMessageAttributes"
----------------------------------- ia."tDTEventTypes"
    SELECT ia."fDTEventTypeAdd"('register');
    SELECT ia."fDTEventTypeAdd"('display');
----------------------------------- ia."tDTEvents"
----------------------------------- ia."tGateways"
    SELECT ia."fGatewayAdd"('тестовый');
----------------------------------- ia."tGatewayIPs"
    SELECT ia."fGatewayIPAdd"('тестовый','127.0.0.1');
    SELECT ia."fGatewayIPAdd"('тестовый','192.168.0.1');
----------------------------------- ia."tNumbers"
----------------------------------- ia."tTexts"
----------------------------------- ia."tImages"
----------------------------------- ia."tBinds"
