----------------------------------- ia."tMessages"
----------------------------------- ia."tMessageAttributes"
----------------------------------- ia."tDTEventTypes"
    SELECT ia."fDTEventTypeAdd"('register');
    SELECT ia."fDTEventTypeAdd"('display');
----------------------------------- ia."tDTEvents"
----------------------------------- ia."tGateways"
    SELECT ia."fGatewayAdd"('тестовый');
----------------------------------- ia."tGatewayIPs"
    SELECT ia."fGatewayIPAdd"('тестовый','213.243.85.167');
    SELECT ia."fGatewayIPAdd"('тестовый','192.168.10.31');
    SELECT ia."fGatewayIPAdd"('тестовый','192.168.10.12');
----------------------------------- ia."tNumbers"
----------------------------------- ia."tTexts"
----------------------------------- ia."tImages"
----------------------------------- ia."tBinds"
