//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Webservice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Webservice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webservice.globalization.Webservice", typeof(Webservice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal storage for session objects is not initialized.
        /// </summary>
        public static string sErrorDBInteract1 {
            get {
                return ResourceManager.GetString("sErrorDBInteract1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session object missing.
        /// </summary>
        public static string sErrorDBInteract2 {
            get {
                return ResourceManager.GetString("sErrorDBInteract2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items for move.
        /// </summary>
        public static string sErrorDBInteract3 {
            get {
                return ResourceManager.GetString("sErrorDBInteract3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the moving items is in a player cach:.
        /// </summary>
        public static string sErrorDBInteract4 {
            get {
                return ResourceManager.GetString("sErrorDBInteract4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to move planned items to the past:.
        /// </summary>
        public static string sErrorDBInteract5 {
            get {
                return ResourceManager.GetString("sErrorDBInteract5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the moving items are cached:.
        /// </summary>
        public static string sErrorDBInteract6 {
            get {
                return ResourceManager.GetString("sErrorDBInteract6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received announcement shift ID is not equal to ID of the current SCR shift.
        /// </summary>
        public static string sErrorDBInteract7 {
            get {
                return ResourceManager.GetString("sErrorDBInteract7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class for clip can&apos;t be null.
        /// </summary>
        public static string sErrorDBInteract8 {
            get {
                return ResourceManager.GetString("sErrorDBInteract8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bumper rotation error:.
        /// </summary>
        public static string sErrorPLImport1 {
            get {
                return ResourceManager.GetString("sErrorPLImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t find any suitable assets while Video International file parse.
        /// </summary>
        public static string sErrorPLImport10 {
            get {
                return ResourceManager.GetString("sErrorPLImport10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block start missing.
        /// </summary>
        public static string sErrorPLImport12 {
            get {
                return ResourceManager.GetString("sErrorPLImport12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset error:.
        /// </summary>
        public static string sErrorPLImport14 {
            get {
                return ResourceManager.GetString("sErrorPLImport14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL ERROR OCCURRED WHILE PLAYLIST IMPORT! CALL DEVELOPER URGENTLY! Please, tell developer next information: there is a problem with playlist import; video international set has an item with duration which exceeds 3.5 minutes:.
        /// </summary>
        public static string sErrorPLImport15 {
            get {
                return ResourceManager.GetString("sErrorPLImport15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items were NOT added to playlist because of zero duration:.
        /// </summary>
        public static string sErrorPLImport16 {
            get {
                return ResourceManager.GetString("sErrorPLImport16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot embed VI advertisement blocks at {0}{1} hours {2} minutes.
        /// </summary>
        public static string sErrorPLImport17 {
            get {
                return ResourceManager.GetString("sErrorPLImport17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing VI block at {0}{1} hours {2} minutes.
        /// </summary>
        public static string sErrorPLImport18 {
            get {
                return ResourceManager.GetString("sErrorPLImport18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content gap found between {0} and {1}.
        /// </summary>
        public static string sErrorPLImport19 {
            get {
                return ResourceManager.GetString("sErrorPLImport19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong PowerGold file format in lines:.
        /// </summary>
        public static string sErrorPLImport2 {
            get {
                return ResourceManager.GetString("sErrorPLImport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot find any suitable assets while design file parsing.
        /// </summary>
        public static string sErrorPLImport20 {
            get {
                return ResourceManager.GetString("sErrorPLImport20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no bindings between PG identifiers and assets:.
        /// </summary>
        public static string sErrorPLImport3 {
            get {
                return ResourceManager.GetString("sErrorPLImport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot find any suitable assets while PowerGold file parsing.
        /// </summary>
        public static string sErrorPLImport4 {
            get {
                return ResourceManager.GetString("sErrorPLImport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot find uploaded file by it&apos;s temporary name:.
        /// </summary>
        public static string sErrorPLImport5 {
            get {
                return ResourceManager.GetString("sErrorPLImport5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing advertisement block name at.
        /// </summary>
        public static string sErrorPLImport6 {
            get {
                return ResourceManager.GetString("sErrorPLImport6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong block start time format:.
        /// </summary>
        public static string sErrorPLImport7 {
            get {
                return ResourceManager.GetString("sErrorPLImport7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing VI advertisement asset ID at {0}{1} hours {2} minutes.
        /// </summary>
        public static string sErrorPLImport8 {
            get {
                return ResourceManager.GetString("sErrorPLImport8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no bindings between VI identifiers and assets:.
        /// </summary>
        public static string sErrorPLImport9 {
            get {
                return ResourceManager.GetString("sErrorPLImport9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION! Next advertisement assets of block at {0} HAVE NOT BEEN USED:.
        /// </summary>
        public static string sNoticePLImport1 {
            get {
                return ResourceManager.GetString("sNoticePLImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset number.
        /// </summary>
        public static string sNoticePLImport2 {
            get {
                return ResourceManager.GetString("sNoticePLImport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plug.
        /// </summary>
        public static string sNoticePLImport4 {
            get {
                return ResourceManager.GetString("sNoticePLImport4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string sNoticePreferences1 {
            get {
                return ResourceManager.GetString("sNoticePreferences1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string sNoticePreferences2 {
            get {
                return ResourceManager.GetString("sNoticePreferences2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared.
        /// </summary>
        public static string sNoticePreferences3 {
            get {
                return ResourceManager.GetString("sNoticePreferences3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On air.
        /// </summary>
        public static string sNoticePreferences4 {
            get {
                return ResourceManager.GetString("sNoticePreferences4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string sNoticePreferences5 {
            get {
                return ResourceManager.GetString("sNoticePreferences5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string sNoticePreferences6 {
            get {
                return ResourceManager.GetString("sNoticePreferences6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string sNoticePreferences7 {
            get {
                return ResourceManager.GetString("sNoticePreferences7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not specified.
        /// </summary>
        public static string sNoticeVJ1 {
            get {
                return ResourceManager.GetString("sNoticeVJ1", resourceCulture);
            }
        }
    }
}
