//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace scr.services.preferences {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Preferences", Namespace="http://replica/ig/services/Preferences.asmx")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(scr.services.preferences.Presentation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(scr.services.preferences.SCR))]
    public partial class Preferences : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Presentation", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Presentation : scr.services.preferences.Preferences {
        
        private scr.services.preferences.ArrayOfString aFontFamiliesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public scr.services.preferences.ArrayOfString aFontFamilies {
            get {
                return this.aFontFamiliesField;
            }
            set {
                if ((object.ReferenceEquals(this.aFontFamiliesField, value) != true)) {
                    this.aFontFamiliesField = value;
                    this.RaisePropertyChanged("aFontFamilies");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCR", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class SCR : scr.services.preferences.Preferences {
        
        private scr.services.preferences.Preset[] aPresetsField;
        
        private scr.services.preferences.Template[] aTemplatesField;
        
        private scr.services.preferences.Plaque[] aPlaquesField;
        
        private string sTemplateChannelMaskField;
        
        private string sTemplatePresetMaskField;
        
        private string sChannelNameField;
        
        private string sDBUserField;
        
        private string sDBPasswdField;
        
        private string sDBIServerNameField;
        
        private int nFragmentBeforeNowField;
        
        private int nFragmentAfterNowField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public scr.services.preferences.Preset[] aPresets {
            get {
                return this.aPresetsField;
            }
            set {
                if ((object.ReferenceEquals(this.aPresetsField, value) != true)) {
                    this.aPresetsField = value;
                    this.RaisePropertyChanged("aPresets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public scr.services.preferences.Template[] aTemplates {
            get {
                return this.aTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.aTemplatesField, value) != true)) {
                    this.aTemplatesField = value;
                    this.RaisePropertyChanged("aTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public scr.services.preferences.Plaque[] aPlaques {
            get {
                return this.aPlaquesField;
            }
            set {
                if ((object.ReferenceEquals(this.aPlaquesField, value) != true)) {
                    this.aPlaquesField = value;
                    this.RaisePropertyChanged("aPlaques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sTemplateChannelMask {
            get {
                return this.sTemplateChannelMaskField;
            }
            set {
                if ((object.ReferenceEquals(this.sTemplateChannelMaskField, value) != true)) {
                    this.sTemplateChannelMaskField = value;
                    this.RaisePropertyChanged("sTemplateChannelMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sTemplatePresetMask {
            get {
                return this.sTemplatePresetMaskField;
            }
            set {
                if ((object.ReferenceEquals(this.sTemplatePresetMaskField, value) != true)) {
                    this.sTemplatePresetMaskField = value;
                    this.RaisePropertyChanged("sTemplatePresetMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sChannelName {
            get {
                return this.sChannelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sChannelNameField, value) != true)) {
                    this.sChannelNameField = value;
                    this.RaisePropertyChanged("sChannelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sDBUser {
            get {
                return this.sDBUserField;
            }
            set {
                if ((object.ReferenceEquals(this.sDBUserField, value) != true)) {
                    this.sDBUserField = value;
                    this.RaisePropertyChanged("sDBUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sDBPasswd {
            get {
                return this.sDBPasswdField;
            }
            set {
                if ((object.ReferenceEquals(this.sDBPasswdField, value) != true)) {
                    this.sDBPasswdField = value;
                    this.RaisePropertyChanged("sDBPasswd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sDBIServerName {
            get {
                return this.sDBIServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sDBIServerNameField, value) != true)) {
                    this.sDBIServerNameField = value;
                    this.RaisePropertyChanged("sDBIServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int nFragmentBeforeNow {
            get {
                return this.nFragmentBeforeNowField;
            }
            set {
                if ((this.nFragmentBeforeNowField.Equals(value) != true)) {
                    this.nFragmentBeforeNowField = value;
                    this.RaisePropertyChanged("nFragmentBeforeNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int nFragmentAfterNow {
            get {
                return this.nFragmentAfterNowField;
            }
            set {
                if ((this.nFragmentAfterNowField.Equals(value) != true)) {
                    this.nFragmentAfterNowField = value;
                    this.RaisePropertyChanged("nFragmentAfterNow");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Preset", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Preset : scr.services.preferences.IdNamePair {
        
        private string sChannelField;
        
        private string sFolderField;
        
        private string sCaptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sChannel {
            get {
                return this.sChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.sChannelField, value) != true)) {
                    this.sChannelField = value;
                    this.RaisePropertyChanged("sChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sFolder {
            get {
                return this.sFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.sFolderField, value) != true)) {
                    this.sFolderField = value;
                    this.RaisePropertyChanged("sFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sCaption {
            get {
                return this.sCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.sCaptionField, value) != true)) {
                    this.sCaptionField = value;
                    this.RaisePropertyChanged("sCaption");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Template : object, System.ComponentModel.INotifyPropertyChanged {
        
        private scr.services.preferences.Bind eBindField;
        
        private string sFileField;
        
        private string sTagField;
        
        private scr.services.preferences.Offset[] aOffsetsField;
        
        private scr.services.preferences.Conflict[] aConflictsField;
        
        private scr.services.preferences.Parameters[] aParametersField;
        
        private scr.services.preferences.PlayerParameters[] aPlayerParametersField;
        
        private scr.services.preferences.Area stScaleVideoField;
        
        private float nPixelAspectRatioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public scr.services.preferences.Bind eBind {
            get {
                return this.eBindField;
            }
            set {
                if ((this.eBindField.Equals(value) != true)) {
                    this.eBindField = value;
                    this.RaisePropertyChanged("eBind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sFile {
            get {
                return this.sFileField;
            }
            set {
                if ((object.ReferenceEquals(this.sFileField, value) != true)) {
                    this.sFileField = value;
                    this.RaisePropertyChanged("sFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sTag {
            get {
                return this.sTagField;
            }
            set {
                if ((object.ReferenceEquals(this.sTagField, value) != true)) {
                    this.sTagField = value;
                    this.RaisePropertyChanged("sTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public scr.services.preferences.Offset[] aOffsets {
            get {
                return this.aOffsetsField;
            }
            set {
                if ((object.ReferenceEquals(this.aOffsetsField, value) != true)) {
                    this.aOffsetsField = value;
                    this.RaisePropertyChanged("aOffsets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public scr.services.preferences.Conflict[] aConflicts {
            get {
                return this.aConflictsField;
            }
            set {
                if ((object.ReferenceEquals(this.aConflictsField, value) != true)) {
                    this.aConflictsField = value;
                    this.RaisePropertyChanged("aConflicts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public scr.services.preferences.Parameters[] aParameters {
            get {
                return this.aParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.aParametersField, value) != true)) {
                    this.aParametersField = value;
                    this.RaisePropertyChanged("aParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public scr.services.preferences.PlayerParameters[] aPlayerParameters {
            get {
                return this.aPlayerParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.aPlayerParametersField, value) != true)) {
                    this.aPlayerParametersField = value;
                    this.RaisePropertyChanged("aPlayerParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public scr.services.preferences.Area stScaleVideo {
            get {
                return this.stScaleVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.stScaleVideoField, value) != true)) {
                    this.stScaleVideoField = value;
                    this.RaisePropertyChanged("stScaleVideo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public float nPixelAspectRatio {
            get {
                return this.nPixelAspectRatioField;
            }
            set {
                if ((this.nPixelAspectRatioField.Equals(value) != true)) {
                    this.nPixelAspectRatioField = value;
                    this.RaisePropertyChanged("nPixelAspectRatio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plaque", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Plaque : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nPresetIDField;
        
        private bool bOpenedField;
        
        private ushort nHeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int nPresetID {
            get {
                return this.nPresetIDField;
            }
            set {
                if ((this.nPresetIDField.Equals(value) != true)) {
                    this.nPresetIDField = value;
                    this.RaisePropertyChanged("nPresetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool bOpened {
            get {
                return this.bOpenedField;
            }
            set {
                if ((this.bOpenedField.Equals(value) != true)) {
                    this.bOpenedField = value;
                    this.RaisePropertyChanged("bOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public ushort nHeight {
            get {
                return this.nHeightField;
            }
            set {
                if ((this.nHeightField.Equals(value) != true)) {
                    this.nHeightField = value;
                    this.RaisePropertyChanged("nHeight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://replica/ig/services/Preferences.asmx", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdNamePair", Namespace="http://replica/ig/services/Preferences.asmx")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(scr.services.preferences.Preset))]
    public partial class IdNamePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long nIDField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long nID {
            get {
                return this.nIDField;
            }
            set {
                if ((this.nIDField.Equals(value) != true)) {
                    this.nIDField = value;
                    this.RaisePropertyChanged("nID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sName {
            get {
                return this.sNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sNameField, value) != true)) {
                    this.sNameField = value;
                    this.RaisePropertyChanged("sName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Area", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Area : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short nTopField;
        
        private short nLeftField;
        
        private ushort nWidthField;
        
        private ushort nHeightField;
        
        private short nRightField;
        
        private short nBottomField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short nTop {
            get {
                return this.nTopField;
            }
            set {
                if ((this.nTopField.Equals(value) != true)) {
                    this.nTopField = value;
                    this.RaisePropertyChanged("nTop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short nLeft {
            get {
                return this.nLeftField;
            }
            set {
                if ((this.nLeftField.Equals(value) != true)) {
                    this.nLeftField = value;
                    this.RaisePropertyChanged("nLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public ushort nWidth {
            get {
                return this.nWidthField;
            }
            set {
                if ((this.nWidthField.Equals(value) != true)) {
                    this.nWidthField = value;
                    this.RaisePropertyChanged("nWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ushort nHeight {
            get {
                return this.nHeightField;
            }
            set {
                if ((this.nHeightField.Equals(value) != true)) {
                    this.nHeightField = value;
                    this.RaisePropertyChanged("nHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public short nRight {
            get {
                return this.nRightField;
            }
            set {
                if ((this.nRightField.Equals(value) != true)) {
                    this.nRightField = value;
                    this.RaisePropertyChanged("nRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public short nBottom {
            get {
                return this.nBottomField;
            }
            set {
                if ((this.nBottomField.Equals(value) != true)) {
                    this.nBottomField = value;
                    this.RaisePropertyChanged("nBottom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bind", Namespace="http://replica/ig/services/Preferences.asmx")]
    public enum Bind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        playlist = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_credits = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_logo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_chat = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_user1 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_user2 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_user3 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        channel_user4 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_logo = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_credits = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_notice = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_credits_advert = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_notice_advert = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_credits_trail = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_notice_trail = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_bumper = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_user1 = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_user2 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_user3 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_user4 = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        preset_sequence = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dtmf_in = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dtmf_out = 23,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offset", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Offset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nPresetIDField;
        
        private int nOffsetInField;
        
        private int nOffsetOutField;
        
        private int nDurationSafeField;
        
        private string sTypeField;
        
        private string sClassField;
        
        private string sPreTypeField;
        
        private string sPreClassField;
        
        private string sNextTypeField;
        
        private string sNextClassField;
        
        private bool bDoOnlyIfLastField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int nPresetID {
            get {
                return this.nPresetIDField;
            }
            set {
                if ((this.nPresetIDField.Equals(value) != true)) {
                    this.nPresetIDField = value;
                    this.RaisePropertyChanged("nPresetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int nOffsetIn {
            get {
                return this.nOffsetInField;
            }
            set {
                if ((this.nOffsetInField.Equals(value) != true)) {
                    this.nOffsetInField = value;
                    this.RaisePropertyChanged("nOffsetIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int nOffsetOut {
            get {
                return this.nOffsetOutField;
            }
            set {
                if ((this.nOffsetOutField.Equals(value) != true)) {
                    this.nOffsetOutField = value;
                    this.RaisePropertyChanged("nOffsetOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int nDurationSafe {
            get {
                return this.nDurationSafeField;
            }
            set {
                if ((this.nDurationSafeField.Equals(value) != true)) {
                    this.nDurationSafeField = value;
                    this.RaisePropertyChanged("nDurationSafe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sType {
            get {
                return this.sTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sTypeField, value) != true)) {
                    this.sTypeField = value;
                    this.RaisePropertyChanged("sType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sClass {
            get {
                return this.sClassField;
            }
            set {
                if ((object.ReferenceEquals(this.sClassField, value) != true)) {
                    this.sClassField = value;
                    this.RaisePropertyChanged("sClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sPreType {
            get {
                return this.sPreTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sPreTypeField, value) != true)) {
                    this.sPreTypeField = value;
                    this.RaisePropertyChanged("sPreType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sPreClass {
            get {
                return this.sPreClassField;
            }
            set {
                if ((object.ReferenceEquals(this.sPreClassField, value) != true)) {
                    this.sPreClassField = value;
                    this.RaisePropertyChanged("sPreClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sNextType {
            get {
                return this.sNextTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sNextTypeField, value) != true)) {
                    this.sNextTypeField = value;
                    this.RaisePropertyChanged("sNextType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sNextClass {
            get {
                return this.sNextClassField;
            }
            set {
                if ((object.ReferenceEquals(this.sNextClassField, value) != true)) {
                    this.sNextClassField = value;
                    this.RaisePropertyChanged("sNextClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool bDoOnlyIfLast {
            get {
                return this.bDoOnlyIfLastField;
            }
            set {
                if ((this.bDoOnlyIfLastField.Equals(value) != true)) {
                    this.bDoOnlyIfLastField = value;
                    this.RaisePropertyChanged("bDoOnlyIfLast");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conflict", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class Conflict : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nPresetIDField;
        
        private scr.services.preferences.Bind eBindField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int nPresetID {
            get {
                return this.nPresetIDField;
            }
            set {
                if ((this.nPresetIDField.Equals(value) != true)) {
                    this.nPresetIDField = value;
                    this.RaisePropertyChanged("nPresetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public scr.services.preferences.Bind eBind {
            get {
                return this.eBindField;
            }
            set {
                if ((this.eBindField.Equals(value) != true)) {
                    this.eBindField = value;
                    this.RaisePropertyChanged("eBind");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameters", Namespace="http://replica/ig/services/Preferences.asmx")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(scr.services.preferences.PlayerParameters))]
    public partial class Parameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nPresetIDField;
        
        private string sTextField;
        
        private bool bIsVisibleField;
        
        private bool bIsEnabledField;
        
        private bool bPlayWithField;
        
        private int nDelayPlayWithField;
        
        private bool bAutostartField;
        
        private scr.services.preferences.FirstAction eFirstActionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int nPresetID {
            get {
                return this.nPresetIDField;
            }
            set {
                if ((this.nPresetIDField.Equals(value) != true)) {
                    this.nPresetIDField = value;
                    this.RaisePropertyChanged("nPresetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sText {
            get {
                return this.sTextField;
            }
            set {
                if ((object.ReferenceEquals(this.sTextField, value) != true)) {
                    this.sTextField = value;
                    this.RaisePropertyChanged("sText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool bIsVisible {
            get {
                return this.bIsVisibleField;
            }
            set {
                if ((this.bIsVisibleField.Equals(value) != true)) {
                    this.bIsVisibleField = value;
                    this.RaisePropertyChanged("bIsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool bIsEnabled {
            get {
                return this.bIsEnabledField;
            }
            set {
                if ((this.bIsEnabledField.Equals(value) != true)) {
                    this.bIsEnabledField = value;
                    this.RaisePropertyChanged("bIsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool bPlayWith {
            get {
                return this.bPlayWithField;
            }
            set {
                if ((this.bPlayWithField.Equals(value) != true)) {
                    this.bPlayWithField = value;
                    this.RaisePropertyChanged("bPlayWith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int nDelayPlayWith {
            get {
                return this.nDelayPlayWithField;
            }
            set {
                if ((this.nDelayPlayWithField.Equals(value) != true)) {
                    this.nDelayPlayWithField = value;
                    this.RaisePropertyChanged("nDelayPlayWith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool bAutostart {
            get {
                return this.bAutostartField;
            }
            set {
                if ((this.bAutostartField.Equals(value) != true)) {
                    this.bAutostartField = value;
                    this.RaisePropertyChanged("bAutostart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public scr.services.preferences.FirstAction eFirstAction {
            get {
                return this.eFirstActionField;
            }
            set {
                if ((this.eFirstActionField.Equals(value) != true)) {
                    this.eFirstActionField = value;
                    this.RaisePropertyChanged("eFirstAction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerParameters", Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class PlayerParameters : scr.services.preferences.Parameters {
        
        private bool bClipChooserVisibleField;
        
        private bool bClipChooserOpenedField;
        
        private bool bOpenedField;
        
        private string sFolderField;
        
        private bool bPlayTopField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bClipChooserVisible {
            get {
                return this.bClipChooserVisibleField;
            }
            set {
                if ((this.bClipChooserVisibleField.Equals(value) != true)) {
                    this.bClipChooserVisibleField = value;
                    this.RaisePropertyChanged("bClipChooserVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool bClipChooserOpened {
            get {
                return this.bClipChooserOpenedField;
            }
            set {
                if ((this.bClipChooserOpenedField.Equals(value) != true)) {
                    this.bClipChooserOpenedField = value;
                    this.RaisePropertyChanged("bClipChooserOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool bOpened {
            get {
                return this.bOpenedField;
            }
            set {
                if ((this.bOpenedField.Equals(value) != true)) {
                    this.bOpenedField = value;
                    this.RaisePropertyChanged("bOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sFolder {
            get {
                return this.sFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.sFolderField, value) != true)) {
                    this.sFolderField = value;
                    this.RaisePropertyChanged("sFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool bPlayTop {
            get {
                return this.bPlayTopField;
            }
            set {
                if ((this.bPlayTopField.Equals(value) != true)) {
                    this.bPlayTopField = value;
                    this.RaisePropertyChanged("bPlayTop");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirstAction", Namespace="http://replica/ig/services/Preferences.asmx")]
    public enum FirstAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        prepare = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        start = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://replica/ig/services/Preferences.asmx", ConfigurationName="services.preferences.PreferencesSoap")]
    public interface PreferencesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Preferences.asmx/SCRGet", ReplyAction="*")]
        System.IAsyncResult BeginSCRGet(scr.services.preferences.SCRGetRequest request, System.AsyncCallback callback, object asyncState);
        
        scr.services.preferences.SCRGetResponse EndSCRGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Preferences.asmx/PresentationGet", ReplyAction="*")]
        System.IAsyncResult BeginPresentationGet(scr.services.preferences.PresentationGetRequest request, System.AsyncCallback callback, object asyncState);
        
        scr.services.preferences.PresentationGetResponse EndPresentationGet(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SCRGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SCRGet", Namespace="http://replica/ig/services/Preferences.asmx", Order=0)]
        public scr.services.preferences.SCRGetRequestBody Body;
        
        public SCRGetRequest() {
        }
        
        public SCRGetRequest(scr.services.preferences.SCRGetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SCRGetRequestBody {
        
        public SCRGetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SCRGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SCRGetResponse", Namespace="http://replica/ig/services/Preferences.asmx", Order=0)]
        public scr.services.preferences.SCRGetResponseBody Body;
        
        public SCRGetResponse() {
        }
        
        public SCRGetResponse(scr.services.preferences.SCRGetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class SCRGetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public scr.services.preferences.SCR SCRGetResult;
        
        public SCRGetResponseBody() {
        }
        
        public SCRGetResponseBody(scr.services.preferences.SCR SCRGetResult) {
            this.SCRGetResult = SCRGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PresentationGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PresentationGet", Namespace="http://replica/ig/services/Preferences.asmx", Order=0)]
        public scr.services.preferences.PresentationGetRequestBody Body;
        
        public PresentationGetRequest() {
        }
        
        public PresentationGetRequest(scr.services.preferences.PresentationGetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PresentationGetRequestBody {
        
        public PresentationGetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PresentationGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PresentationGetResponse", Namespace="http://replica/ig/services/Preferences.asmx", Order=0)]
        public scr.services.preferences.PresentationGetResponseBody Body;
        
        public PresentationGetResponse() {
        }
        
        public PresentationGetResponse(scr.services.preferences.PresentationGetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://replica/ig/services/Preferences.asmx")]
    public partial class PresentationGetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public scr.services.preferences.Presentation PresentationGetResult;
        
        public PresentationGetResponseBody() {
        }
        
        public PresentationGetResponseBody(scr.services.preferences.Presentation PresentationGetResult) {
            this.PresentationGetResult = PresentationGetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PreferencesSoapChannel : scr.services.preferences.PreferencesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCRGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SCRGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public scr.services.preferences.SCR Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((scr.services.preferences.SCR)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresentationGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PresentationGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public scr.services.preferences.Presentation Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((scr.services.preferences.Presentation)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreferencesSoapClient : System.ServiceModel.ClientBase<scr.services.preferences.PreferencesSoap>, scr.services.preferences.PreferencesSoap {
        
        private BeginOperationDelegate onBeginSCRGetDelegate;
        
        private EndOperationDelegate onEndSCRGetDelegate;
        
        private System.Threading.SendOrPostCallback onSCRGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginPresentationGetDelegate;
        
        private EndOperationDelegate onEndPresentationGetDelegate;
        
        private System.Threading.SendOrPostCallback onPresentationGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PreferencesSoapClient() {
        }
        
        public PreferencesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreferencesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreferencesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreferencesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SCRGetCompletedEventArgs> SCRGetCompleted;
        
        public event System.EventHandler<PresentationGetCompletedEventArgs> PresentationGetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult scr.services.preferences.PreferencesSoap.BeginSCRGet(scr.services.preferences.SCRGetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSCRGet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSCRGet(System.AsyncCallback callback, object asyncState) {
            scr.services.preferences.SCRGetRequest inValue = new scr.services.preferences.SCRGetRequest();
            inValue.Body = new scr.services.preferences.SCRGetRequestBody();
            return ((scr.services.preferences.PreferencesSoap)(this)).BeginSCRGet(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        scr.services.preferences.SCRGetResponse scr.services.preferences.PreferencesSoap.EndSCRGet(System.IAsyncResult result) {
            return base.Channel.EndSCRGet(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private scr.services.preferences.SCR EndSCRGet(System.IAsyncResult result) {
            scr.services.preferences.SCRGetResponse retVal = ((scr.services.preferences.PreferencesSoap)(this)).EndSCRGet(result);
            return retVal.Body.SCRGetResult;
        }
        
        private System.IAsyncResult OnBeginSCRGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginSCRGet(callback, asyncState);
        }
        
        private object[] OnEndSCRGet(System.IAsyncResult result) {
            scr.services.preferences.SCR retVal = this.EndSCRGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSCRGetCompleted(object state) {
            if ((this.SCRGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SCRGetCompleted(this, new SCRGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SCRGetAsync() {
            this.SCRGetAsync(null);
        }
        
        public void SCRGetAsync(object userState) {
            if ((this.onBeginSCRGetDelegate == null)) {
                this.onBeginSCRGetDelegate = new BeginOperationDelegate(this.OnBeginSCRGet);
            }
            if ((this.onEndSCRGetDelegate == null)) {
                this.onEndSCRGetDelegate = new EndOperationDelegate(this.OnEndSCRGet);
            }
            if ((this.onSCRGetCompletedDelegate == null)) {
                this.onSCRGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSCRGetCompleted);
            }
            base.InvokeAsync(this.onBeginSCRGetDelegate, null, this.onEndSCRGetDelegate, this.onSCRGetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult scr.services.preferences.PreferencesSoap.BeginPresentationGet(scr.services.preferences.PresentationGetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPresentationGet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginPresentationGet(System.AsyncCallback callback, object asyncState) {
            scr.services.preferences.PresentationGetRequest inValue = new scr.services.preferences.PresentationGetRequest();
            inValue.Body = new scr.services.preferences.PresentationGetRequestBody();
            return ((scr.services.preferences.PreferencesSoap)(this)).BeginPresentationGet(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        scr.services.preferences.PresentationGetResponse scr.services.preferences.PreferencesSoap.EndPresentationGet(System.IAsyncResult result) {
            return base.Channel.EndPresentationGet(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private scr.services.preferences.Presentation EndPresentationGet(System.IAsyncResult result) {
            scr.services.preferences.PresentationGetResponse retVal = ((scr.services.preferences.PreferencesSoap)(this)).EndPresentationGet(result);
            return retVal.Body.PresentationGetResult;
        }
        
        private System.IAsyncResult OnBeginPresentationGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginPresentationGet(callback, asyncState);
        }
        
        private object[] OnEndPresentationGet(System.IAsyncResult result) {
            scr.services.preferences.Presentation retVal = this.EndPresentationGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPresentationGetCompleted(object state) {
            if ((this.PresentationGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PresentationGetCompleted(this, new PresentationGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PresentationGetAsync() {
            this.PresentationGetAsync(null);
        }
        
        public void PresentationGetAsync(object userState) {
            if ((this.onBeginPresentationGetDelegate == null)) {
                this.onBeginPresentationGetDelegate = new BeginOperationDelegate(this.OnBeginPresentationGet);
            }
            if ((this.onEndPresentationGetDelegate == null)) {
                this.onEndPresentationGetDelegate = new EndOperationDelegate(this.OnEndPresentationGet);
            }
            if ((this.onPresentationGetCompletedDelegate == null)) {
                this.onPresentationGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPresentationGetCompleted);
            }
            base.InvokeAsync(this.onBeginPresentationGetDelegate, null, this.onEndPresentationGetDelegate, this.onPresentationGetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override scr.services.preferences.PreferencesSoap CreateChannel() {
            return new PreferencesSoapClientChannel(this);
        }
        
        private class PreferencesSoapClientChannel : ChannelBase<scr.services.preferences.PreferencesSoap>, scr.services.preferences.PreferencesSoap {
            
            public PreferencesSoapClientChannel(System.ServiceModel.ClientBase<scr.services.preferences.PreferencesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSCRGet(scr.services.preferences.SCRGetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SCRGet", _args, callback, asyncState);
                return _result;
            }
            
            public scr.services.preferences.SCRGetResponse EndSCRGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                scr.services.preferences.SCRGetResponse _result = ((scr.services.preferences.SCRGetResponse)(base.EndInvoke("SCRGet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPresentationGet(scr.services.preferences.PresentationGetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PresentationGet", _args, callback, asyncState);
                return _result;
            }
            
            public scr.services.preferences.PresentationGetResponse EndPresentationGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                scr.services.preferences.PresentationGetResponse _result = ((scr.services.preferences.PresentationGetResponse)(base.EndInvoke("PresentationGet", _args, result)));
                return _result;
            }
        }
    }
}
