//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Helper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Helper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("helpers.replica.globalization.Helper", typeof(Helper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        public static string sAdvertisement {
            get {
                return ResourceManager.GetString("sAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvertisementBlock.
        /// </summary>
        public static string sAdvertisementBlock {
            get {
                return ResourceManager.GetString("sAdvertisementBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string sAlbum {
            get {
                return ResourceManager.GetString("sAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string sArchive {
            get {
                return ResourceManager.GetString("sArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string sArtist {
            get {
                return ResourceManager.GetString("sArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string sArtists {
            get {
                return ResourceManager.GetString("sArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists missing.
        /// </summary>
        public static string sArtistsMissing {
            get {
                return ResourceManager.GetString("sArtistsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID.
        /// </summary>
        public static string sAssetID {
            get {
                return ResourceManager.GetString("sAssetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset name.
        /// </summary>
        public static string sAssetName {
            get {
                return ResourceManager.GetString("sAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string sAssets {
            get {
                return ResourceManager.GetString("sAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset search.
        /// </summary>
        public static string sAssetSearch {
            get {
                return ResourceManager.GetString("sAssetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper.
        /// </summary>
        public static string sBumper {
            get {
                return ResourceManager.GetString("sBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string sChannel {
            get {
                return ResourceManager.GetString("sChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string sChat {
            get {
                return ResourceManager.GetString("sChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string sCheckPoint {
            get {
                return ResourceManager.GetString("sCheckPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string sClass {
            get {
                return ResourceManager.GetString("sClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        public static string sClip {
            get {
                return ResourceManager.GetString("sClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips.
        /// </summary>
        public static string sClips {
            get {
                return ResourceManager.GetString("sClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clockface.
        /// </summary>
        public static string sClockFace {
            get {
                return ResourceManager.GetString("sClockFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl.
        /// </summary>
        public static string sCrawl {
            get {
                return ResourceManager.GetString("sCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawls.
        /// </summary>
        public static string sCrawls {
            get {
                return ResourceManager.GetString("sCrawls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue.
        /// </summary>
        public static string sCue {
            get {
                return ResourceManager.GetString("sCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cues.
        /// </summary>
        public static string sCues {
            get {
                return ResourceManager.GetString("sCues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cues class.
        /// </summary>
        public static string sCuesClass {
            get {
                return ResourceManager.GetString("sCuesClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current item.
        /// </summary>
        public static string sCurrentItem {
            get {
                return ResourceManager.GetString("sCurrentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom values.
        /// </summary>
        public static string sCustomValues {
            get {
                return ResourceManager.GetString("sCustomValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutted.
        /// </summary>
        public static string sCutted {
            get {
                return ResourceManager.GetString("sCutted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string sDays {
            get {
                return ResourceManager.GetString("sDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string sDesign {
            get {
                return ResourceManager.GetString("sDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string sDuration {
            get {
                return ResourceManager.GetString("sDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit artist name.
        /// </summary>
        public static string sEditArtistName {
            get {
                return ResourceManager.GetString("sEditArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string sEnd {
            get {
                return ResourceManager.GetString("sEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string sEnded {
            get {
                return ResourceManager.GetString("sEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string sEpisode {
            get {
                return ResourceManager.GetString("sEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equal.
        /// </summary>
        public static string sEqual {
            get {
                return ResourceManager.GetString("sEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined status.
        /// </summary>
        public static string sErrorDBInteract1 {
            get {
                return ResourceManager.GetString("sErrorDBInteract1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong status.
        /// </summary>
        public static string sErrorDBInteract2 {
            get {
                return ResourceManager.GetString("sErrorDBInteract2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR shift adding error.
        /// </summary>
        public static string sErrorDBInteract3 {
            get {
                return ResourceManager.GetString("sErrorDBInteract3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR shift starting error.
        /// </summary>
        public static string sErrorDBInteract4 {
            get {
                return ResourceManager.GetString("sErrorDBInteract4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR shift stopping error.
        /// </summary>
        public static string sErrorDBInteract5 {
            get {
                return ResourceManager.GetString("sErrorDBInteract5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File timings error.
        /// </summary>
        public static string sErrorGettingFileTimings {
            get {
                return ResourceManager.GetString("sErrorGettingFileTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no live.
        /// </summary>
        public static string sErrorLiveIsMissing {
            get {
                return ResourceManager.GetString("sErrorLiveIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists list receive error.
        /// </summary>
        public static string sErrorReceiveArtistsList {
            get {
                return ResourceManager.GetString("sErrorReceiveArtistsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets list receive error.
        /// </summary>
        public static string sErrorReceiveAssetsList {
            get {
                return ResourceManager.GetString("sErrorReceiveAssetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles list receive error.
        /// </summary>
        public static string sErrorReceiveStylesList {
            get {
                return ResourceManager.GetString("sErrorReceiveStylesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event start.
        /// </summary>
        public static string sEventStart {
            get {
                return ResourceManager.GetString("sEventStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ID.
        /// </summary>
        public static string sFileID {
            get {
                return ResourceManager.GetString("sFileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string sFiles {
            get {
                return ResourceManager.GetString("sFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finishing.
        /// </summary>
        public static string sFinishing {
            get {
                return ResourceManager.GetString("sFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string sFirst {
            get {
                return ResourceManager.GetString("sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font name.
        /// </summary>
        public static string sFontName {
            get {
                return ResourceManager.GetString("sFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string sFontSize {
            get {
                return ResourceManager.GetString("sFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string sFor {
            get {
                return ResourceManager.GetString("sFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string sFormat {
            get {
                return ResourceManager.GetString("sFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frames qty.
        /// </summary>
        public static string sFramesQty {
            get {
                return ResourceManager.GetString("sFramesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string sGrid {
            get {
                return ResourceManager.GetString("sGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string sHours {
            get {
                return ResourceManager.GetString("sHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string sInsert {
            get {
                return ResourceManager.GetString("sInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it should be fixed with.
        /// </summary>
        public static string sItShouldBeFixedWith {
            get {
                return ResourceManager.GetString("sItShouldBeFixedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string sLeft {
            get {
                return ResourceManager.GetString("sLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        public static string sLess {
            get {
                return ResourceManager.GetString("sLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line1.
        /// </summary>
        public static string sLine1 {
            get {
                return ResourceManager.GetString("sLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line2.
        /// </summary>
        public static string sLine2 {
            get {
                return ResourceManager.GetString("sLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string sLive {
            get {
                return ResourceManager.GetString("sLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string sLogo {
            get {
                return ResourceManager.GetString("sLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string sMedia {
            get {
                return ResourceManager.GetString("sMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string sMessages {
            get {
                return ResourceManager.GetString("sMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix.
        /// </summary>
        public static string sMix {
            get {
                return ResourceManager.GetString("sMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string sMore {
            get {
                return ResourceManager.GetString("sMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next items were not added:.
        /// </summary>
        public static string sNextItemsWereNotAdded {
            get {
                return ResourceManager.GetString("sNextItemsWereNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset prepared effect?.
        /// </summary>
        public static string sNoticeTemplateButton1 {
            get {
                return ResourceManager.GetString("sNoticeTemplateButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On air.
        /// </summary>
        public static string sOnAir {
            get {
                return ResourceManager.GetString("sOnAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string sPalette {
            get {
                return ResourceManager.GetString("sPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter parent asset ID:.
        /// </summary>
        public static string sParentAssetID {
            get {
                return ResourceManager.GetString("sParentAssetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string sPart {
            get {
                return ResourceManager.GetString("sPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string sPersons {
            get {
                return ResourceManager.GetString("sPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person search.
        /// </summary>
        public static string sPersonSearch {
            get {
                return ResourceManager.GetString("sPersonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string sPhoto {
            get {
                return ResourceManager.GetString("sPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string sPlaylist {
            get {
                return ResourceManager.GetString("sPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist archive.
        /// </summary>
        public static string sPlaylistArchive {
            get {
                return ResourceManager.GetString("sPlaylistArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist import.
        /// </summary>
        public static string sPlaylistImport {
            get {
                return ResourceManager.GetString("sPlaylistImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist item properties.
        /// </summary>
        public static string sPlaylistItemProperties {
            get {
                return ResourceManager.GetString("sPlaylistItemProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist items move.
        /// </summary>
        public static string sPlaylistItemsMove {
            get {
                return ResourceManager.GetString("sPlaylistItemsMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlists integration.
        /// </summary>
        public static string sPlaylistsIntegration {
            get {
                return ResourceManager.GetString("sPlaylistsIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug.
        /// </summary>
        public static string sPlug {
            get {
                return ResourceManager.GetString("sPlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possessor.
        /// </summary>
        public static string sPossessor {
            get {
                return ResourceManager.GetString("sPossessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string sProgram {
            get {
                return ResourceManager.GetString("sProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string sPrograms {
            get {
                return ResourceManager.GetString("sPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program type.
        /// </summary>
        public static string sProgramType {
            get {
                return ResourceManager.GetString("sProgramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string sPromo {
            get {
                return ResourceManager.GetString("sPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string sQuality {
            get {
                return ResourceManager.GetString("sQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string sRecalculate {
            get {
                return ResourceManager.GetString("sRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recalculate timings.
        /// </summary>
        public static string sRecalculateTimings {
            get {
                return ResourceManager.GetString("sRecalculateTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculation.
        /// </summary>
        public static string sRecalculation {
            get {
                return ResourceManager.GetString("sRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh playlist.
        /// </summary>
        public static string sRefreshPlaylist {
            get {
                return ResourceManager.GetString("sRefreshPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remix.
        /// </summary>
        public static string sRemix {
            get {
                return ResourceManager.GetString("sRemix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing assets&apos; parent.
        /// </summary>
        public static string sRemovingAssetsParent {
            get {
                return ResourceManager.GetString("sRemovingAssetsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string sRotation {
            get {
                return ResourceManager.GetString("sRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string sSec {
            get {
                return ResourceManager.GetString("sSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string sSecond {
            get {
                return ResourceManager.GetString("sSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select asset.
        /// </summary>
        public static string sSelectAsset {
            get {
                return ResourceManager.GetString("sSelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clip.
        /// </summary>
        public static string sSelectClip {
            get {
                return ResourceManager.GetString("sSelectClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string sSequence {
            get {
                return ResourceManager.GetString("sSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string sSeries {
            get {
                return ResourceManager.GetString("sSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server files path:.
        /// </summary>
        public static string sServerFilesPath {
            get {
                return ResourceManager.GetString("sServerFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set parent.
        /// </summary>
        public static string sSetParent {
            get {
                return ResourceManager.GetString("sSetParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting assets parent.
        /// </summary>
        public static string sSettingAssetsParent {
            get {
                return ResourceManager.GetString("sSettingAssetsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string sSong {
            get {
                return ResourceManager.GetString("sSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string sSound {
            get {
                return ResourceManager.GetString("sSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string sSpeed {
            get {
                return ResourceManager.GetString("sSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string sStart {
            get {
                return ResourceManager.GetString("sStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string sStartTime {
            get {
                return ResourceManager.GetString("sStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string sStatistics {
            get {
                return ResourceManager.GetString("sStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string sStop {
            get {
                return ResourceManager.GetString("sStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string sStorage {
            get {
                return ResourceManager.GetString("sStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string sStyles {
            get {
                return ResourceManager.GetString("sStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles missing.
        /// </summary>
        public static string sStylesMissing {
            get {
                return ResourceManager.GetString("sStylesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        public static string sTemplateName {
            get {
                return ResourceManager.GetString("sTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string sTemplates {
            get {
                return ResourceManager.GetString("sTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string sThird {
            get {
                return ResourceManager.GetString("sThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timings.
        /// </summary>
        public static string sTimings {
            get {
                return ResourceManager.GetString("sTimings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string sTrailer {
            get {
                return ResourceManager.GetString("sTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        public static string sTrailers {
            get {
                return ResourceManager.GetString("sTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unset parent.
        /// </summary>
        public static string sUnsetParent {
            get {
                return ResourceManager.GetString("sUnsetParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proccessing uploaded files.
        /// </summary>
        public static string sUploadedFilesAnalyzing {
            get {
                return ResourceManager.GetString("sUploadedFilesAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string sVideo {
            get {
                return ResourceManager.GetString("sVideo", resourceCulture);
            }
        }
    }
}
