/********************************** adm."tCommands" ***************************************/
INSERT INTO adm."tCommands" ("sName") VALUES ('player_start');
INSERT INTO adm."tCommands" ("sName") VALUES ('player_pause');
INSERT INTO adm."tCommands" ("sName") VALUES ('player_stop');
INSERT INTO adm."tCommands" ("sName") VALUES ('player_skip');
INSERT INTO adm."tCommands" ("sName") VALUES ('playlist_update');
INSERT INTO adm."tCommands" ("sName") VALUES ('cues_template_show');
INSERT INTO adm."tCommands" ("sName") VALUES ('cues_template_hide');
INSERT INTO adm."tCommands" ("sName") VALUES ('playlist_item_duration_update');
INSERT INTO adm."tCommands" ("sName") VALUES ('asset_duration_update');
INSERT INTO adm."tCommands" ("sName") VALUES ('asset_file_update');
INSERT INTO adm."tCommands" ("sName") VALUES ('file_upload');
INSERT INTO adm."tCommands" ("sName") VALUES ('file_duration_get');
INSERT INTO adm."tCommands" ("sName") VALUES ('playlist_recalculate');
INSERT INTO adm."tCommands" ("sName") VALUES ('service_start');
INSERT INTO adm."tCommands" ("sName") VALUES ('service_stop');
INSERT INTO adm."tCommands" ("sName") VALUES ('failover_sync');
INSERT INTO adm."tCommands" ("sName") VALUES ('failover_skip');
/********************************** adm."tCommandStatuses" ********************************/
INSERT INTO adm."tCommandStatuses" VALUES (1, 'waiting');
INSERT INTO adm."tCommandStatuses" VALUES (2, 'proccessing');
INSERT INTO adm."tCommandStatuses" VALUES (3, 'failed');
INSERT INTO adm."tCommandStatuses" VALUES (4, 'succeed');
/********************************** adm."tPreferenceClasses" ******************************/
SELECT adm."fPreferenceClassAdd"('runtime', true);
SELECT adm."fPreferenceClassAdd"('grid', true);
SELECT adm."fPreferenceClassAdd"('social', true);
/********************************** adm."tPreferences" ************************************/
SELECT adm."fPreferenceAdd"('runtime', 'scr_onair', 'false', true);
SELECT adm."fPreferenceAdd"('runtime', 'storage_free_space', '0', true);
SELECT adm."fPreferenceAdd"('grid', 'clip_duration_minimum_for_cut', '150', true);
SELECT adm."fPreferenceAdd"('grid', 'pli_duration_minimum', '5', true);
/********************************** adm."tTransliteration" ********************************/
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('а', 'a');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('б', 'b');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('в', 'v');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('г', 'g');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('д', 'd');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('е', 'e');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ё', 'e');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ж', 'zh');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('з', 'z');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('и', 'i');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('й', 'i');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('к', 'k');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('л', 'l');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('м', 'm');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('н', 'n');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('о', 'o');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('п', 'p');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('р', 'r');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('с', 's');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('т', 't');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('у', 'u');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ф', 'f');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('х', 'h');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ц', 'c');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ч', 'ch');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ш', 'sh');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('щ', 'w');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ы', 'y');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('э', 'e');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('ю', 'yu');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('я', 'ya');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (' ', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (',', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('.', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (':', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (';', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('''', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('"', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('[', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('{', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (']', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('}', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('-', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('=', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('+', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('\', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('|', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('*', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('/', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('`', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('~', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('!', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('@', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('#', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('$', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('%', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('^', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('(', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES (')', '_');
INSERT INTO adm."tTransliteration" ("sSource", "sTarget") VALUES ('?', '_');