//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace presentation.sl.services.cues {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://replica/ig/services/Cues.asmx", ConfigurationName="services.cues.CuesSoap")]
    public interface CuesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemCreate(string sPreset, string sFile, UserReplacement[] aUserReplacements, System.AsyncCallback callback, object asyncState);
        
        presentation.sl.services.cues.Item EndItemCreate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemsRunningGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemsRunningGet(System.AsyncCallback callback, object asyncState);
        
        Item[] EndItemsRunningGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/Init", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginInit(ulong nClientBrowserID, System.AsyncCallback callback, object asyncState);
        
        string EndInit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState);
        
        void EndPing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemsUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemsUpdate(Item[] aItems, System.AsyncCallback callback, object asyncState);
        
        Item[] EndItemsUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemDelete(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState);
        
        bool EndItemDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemPrepare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemPrepare(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState);
        
        bool EndItemPrepare(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemStart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemStart(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState);
        
        bool EndItemStart(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/ItemStop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginItemStop(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState);
        
        bool EndItemStop(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/DeviceDownStreamKeyerDisable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginDeviceDownStreamKeyerDisable(System.AsyncCallback callback, object asyncState);
        
        void EndDeviceDownStreamKeyerDisable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://replica/ig/services/Cues.asmx/DeviceDownStreamKeyerEnable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginDeviceDownStreamKeyerEnable(byte nLevel, bool bInternal, System.AsyncCallback callback, object asyncState);
        
        void EndDeviceDownStreamKeyerEnable(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replica/ig/services/Cues.asmx")]
    public partial class UserReplacement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sKeyField;
        
        private string sValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sKey {
            get {
                return this.sKeyField;
            }
            set {
                this.sKeyField = value;
                this.RaisePropertyChanged("sKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sValue {
            get {
                return this.sValueField;
            }
            set {
                this.sValueField = value;
                this.RaisePropertyChanged("sValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Template))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replica/ig/services/Cues.asmx")]
    public abstract partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong nIDField;
        
        private string sPresetField;
        
        private System.DateTime dtStatusChangedField;
        
        private Status eStatusField;
        
        private string sInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong nID {
            get {
                return this.nIDField;
            }
            set {
                this.nIDField = value;
                this.RaisePropertyChanged("nID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sPreset {
            get {
                return this.sPresetField;
            }
            set {
                this.sPresetField = value;
                this.RaisePropertyChanged("sPreset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime dtStatusChanged {
            get {
                return this.dtStatusChangedField;
            }
            set {
                this.dtStatusChangedField = value;
                this.RaisePropertyChanged("dtStatusChanged");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Status eStatus {
            get {
                return this.eStatusField;
            }
            set {
                this.eStatusField = value;
                this.RaisePropertyChanged("eStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sInfo {
            get {
                return this.sInfoField;
            }
            set {
                this.sInfoField = value;
                this.RaisePropertyChanged("sInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replica/ig/services/Cues.asmx")]
    public enum Status {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Idle,
        
        /// <remarks/>
        Prepared,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replica/ig/services/Cues.asmx")]
    public partial class Template : Item {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuesSoapChannel : presentation.sl.services.cues.CuesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public presentation.sl.services.cues.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((presentation.sl.services.cues.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemsRunningGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemsRunningGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Item[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Item[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemsUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemsUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Item[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Item[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemPrepareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemPrepareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemStopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ItemStopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuesSoapClient : System.ServiceModel.ClientBase<presentation.sl.services.cues.CuesSoap>, presentation.sl.services.cues.CuesSoap {
        
        private BeginOperationDelegate onBeginItemCreateDelegate;
        
        private EndOperationDelegate onEndItemCreateDelegate;
        
        private System.Threading.SendOrPostCallback onItemCreateCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemsRunningGetDelegate;
        
        private EndOperationDelegate onEndItemsRunningGetDelegate;
        
        private System.Threading.SendOrPostCallback onItemsRunningGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginInitDelegate;
        
        private EndOperationDelegate onEndInitDelegate;
        
        private System.Threading.SendOrPostCallback onInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemsUpdateDelegate;
        
        private EndOperationDelegate onEndItemsUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onItemsUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemDeleteDelegate;
        
        private EndOperationDelegate onEndItemDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onItemDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemPrepareDelegate;
        
        private EndOperationDelegate onEndItemPrepareDelegate;
        
        private System.Threading.SendOrPostCallback onItemPrepareCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemStartDelegate;
        
        private EndOperationDelegate onEndItemStartDelegate;
        
        private System.Threading.SendOrPostCallback onItemStartCompletedDelegate;
        
        private BeginOperationDelegate onBeginItemStopDelegate;
        
        private EndOperationDelegate onEndItemStopDelegate;
        
        private System.Threading.SendOrPostCallback onItemStopCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeviceDownStreamKeyerDisableDelegate;
        
        private EndOperationDelegate onEndDeviceDownStreamKeyerDisableDelegate;
        
        private System.Threading.SendOrPostCallback onDeviceDownStreamKeyerDisableCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeviceDownStreamKeyerEnableDelegate;
        
        private EndOperationDelegate onEndDeviceDownStreamKeyerEnableDelegate;
        
        private System.Threading.SendOrPostCallback onDeviceDownStreamKeyerEnableCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CuesSoapClient() {
        }
        
        public CuesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ItemCreateCompletedEventArgs> ItemCreateCompleted;
        
        public event System.EventHandler<ItemsRunningGetCompletedEventArgs> ItemsRunningGetCompleted;
        
        public event System.EventHandler<InitCompletedEventArgs> InitCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PingCompleted;
        
        public event System.EventHandler<ItemsUpdateCompletedEventArgs> ItemsUpdateCompleted;
        
        public event System.EventHandler<ItemDeleteCompletedEventArgs> ItemDeleteCompleted;
        
        public event System.EventHandler<ItemPrepareCompletedEventArgs> ItemPrepareCompleted;
        
        public event System.EventHandler<ItemStartCompletedEventArgs> ItemStartCompleted;
        
        public event System.EventHandler<ItemStopCompletedEventArgs> ItemStopCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeviceDownStreamKeyerDisableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeviceDownStreamKeyerEnableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemCreate(string sPreset, string sFile, UserReplacement[] aUserReplacements, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemCreate(sPreset, sFile, aUserReplacements, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        presentation.sl.services.cues.Item presentation.sl.services.cues.CuesSoap.EndItemCreate(System.IAsyncResult result) {
            return base.Channel.EndItemCreate(result);
        }
        
        private System.IAsyncResult OnBeginItemCreate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sPreset = ((string)(inValues[0]));
            string sFile = ((string)(inValues[1]));
            UserReplacement[] aUserReplacements = ((UserReplacement[])(inValues[2]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemCreate(sPreset, sFile, aUserReplacements, callback, asyncState);
        }
        
        private object[] OnEndItemCreate(System.IAsyncResult result) {
            presentation.sl.services.cues.Item retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemCreate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemCreateCompleted(object state) {
            if ((this.ItemCreateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemCreateCompleted(this, new ItemCreateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemCreateAsync(string sPreset, string sFile, UserReplacement[] aUserReplacements) {
            this.ItemCreateAsync(sPreset, sFile, aUserReplacements, null);
        }
        
        public void ItemCreateAsync(string sPreset, string sFile, UserReplacement[] aUserReplacements, object userState) {
            if ((this.onBeginItemCreateDelegate == null)) {
                this.onBeginItemCreateDelegate = new BeginOperationDelegate(this.OnBeginItemCreate);
            }
            if ((this.onEndItemCreateDelegate == null)) {
                this.onEndItemCreateDelegate = new EndOperationDelegate(this.OnEndItemCreate);
            }
            if ((this.onItemCreateCompletedDelegate == null)) {
                this.onItemCreateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemCreateCompleted);
            }
            base.InvokeAsync(this.onBeginItemCreateDelegate, new object[] {
                        sPreset,
                        sFile,
                        aUserReplacements}, this.onEndItemCreateDelegate, this.onItemCreateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemsRunningGet(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemsRunningGet(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Item[] presentation.sl.services.cues.CuesSoap.EndItemsRunningGet(System.IAsyncResult result) {
            return base.Channel.EndItemsRunningGet(result);
        }
        
        private System.IAsyncResult OnBeginItemsRunningGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemsRunningGet(callback, asyncState);
        }
        
        private object[] OnEndItemsRunningGet(System.IAsyncResult result) {
            Item[] retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemsRunningGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemsRunningGetCompleted(object state) {
            if ((this.ItemsRunningGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemsRunningGetCompleted(this, new ItemsRunningGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemsRunningGetAsync() {
            this.ItemsRunningGetAsync(null);
        }
        
        public void ItemsRunningGetAsync(object userState) {
            if ((this.onBeginItemsRunningGetDelegate == null)) {
                this.onBeginItemsRunningGetDelegate = new BeginOperationDelegate(this.OnBeginItemsRunningGet);
            }
            if ((this.onEndItemsRunningGetDelegate == null)) {
                this.onEndItemsRunningGetDelegate = new EndOperationDelegate(this.OnEndItemsRunningGet);
            }
            if ((this.onItemsRunningGetCompletedDelegate == null)) {
                this.onItemsRunningGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemsRunningGetCompleted);
            }
            base.InvokeAsync(this.onBeginItemsRunningGetDelegate, null, this.onEndItemsRunningGetDelegate, this.onItemsRunningGetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginInit(ulong nClientBrowserID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInit(nClientBrowserID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string presentation.sl.services.cues.CuesSoap.EndInit(System.IAsyncResult result) {
            return base.Channel.EndInit(result);
        }
        
        private System.IAsyncResult OnBeginInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ulong nClientBrowserID = ((ulong)(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginInit(nClientBrowserID, callback, asyncState);
        }
        
        private object[] OnEndInit(System.IAsyncResult result) {
            string retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndInit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInitCompleted(object state) {
            if ((this.InitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InitCompleted(this, new InitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InitAsync(ulong nClientBrowserID) {
            this.InitAsync(nClientBrowserID, null);
        }
        
        public void InitAsync(ulong nClientBrowserID, object userState) {
            if ((this.onBeginInitDelegate == null)) {
                this.onBeginInitDelegate = new BeginOperationDelegate(this.OnBeginInit);
            }
            if ((this.onEndInitDelegate == null)) {
                this.onEndInitDelegate = new EndOperationDelegate(this.OnEndInit);
            }
            if ((this.onInitCompletedDelegate == null)) {
                this.onInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInitCompleted);
            }
            base.InvokeAsync(this.onBeginInitDelegate, new object[] {
                        nClientBrowserID}, this.onEndInitDelegate, this.onInitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginPing(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void presentation.sl.services.cues.CuesSoap.EndPing(System.IAsyncResult result) {
            base.Channel.EndPing(result);
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginPing(callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            ((presentation.sl.services.cues.CuesSoap)(this)).EndPing(result);
            return null;
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        public void PingAsync(object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, null, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemsUpdate(Item[] aItems, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemsUpdate(aItems, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Item[] presentation.sl.services.cues.CuesSoap.EndItemsUpdate(System.IAsyncResult result) {
            return base.Channel.EndItemsUpdate(result);
        }
        
        private System.IAsyncResult OnBeginItemsUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Item[] aItems = ((Item[])(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemsUpdate(aItems, callback, asyncState);
        }
        
        private object[] OnEndItemsUpdate(System.IAsyncResult result) {
            Item[] retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemsUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemsUpdateCompleted(object state) {
            if ((this.ItemsUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemsUpdateCompleted(this, new ItemsUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemsUpdateAsync(Item[] aItems) {
            this.ItemsUpdateAsync(aItems, null);
        }
        
        public void ItemsUpdateAsync(Item[] aItems, object userState) {
            if ((this.onBeginItemsUpdateDelegate == null)) {
                this.onBeginItemsUpdateDelegate = new BeginOperationDelegate(this.OnBeginItemsUpdate);
            }
            if ((this.onEndItemsUpdateDelegate == null)) {
                this.onEndItemsUpdateDelegate = new EndOperationDelegate(this.OnEndItemsUpdate);
            }
            if ((this.onItemsUpdateCompletedDelegate == null)) {
                this.onItemsUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemsUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginItemsUpdateDelegate, new object[] {
                        aItems}, this.onEndItemsUpdateDelegate, this.onItemsUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemDelete(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemDelete(cItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool presentation.sl.services.cues.CuesSoap.EndItemDelete(System.IAsyncResult result) {
            return base.Channel.EndItemDelete(result);
        }
        
        private System.IAsyncResult OnBeginItemDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            presentation.sl.services.cues.Item cItem = ((presentation.sl.services.cues.Item)(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemDelete(cItem, callback, asyncState);
        }
        
        private object[] OnEndItemDelete(System.IAsyncResult result) {
            bool retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemDeleteCompleted(object state) {
            if ((this.ItemDeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemDeleteCompleted(this, new ItemDeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemDeleteAsync(presentation.sl.services.cues.Item cItem) {
            this.ItemDeleteAsync(cItem, null);
        }
        
        public void ItemDeleteAsync(presentation.sl.services.cues.Item cItem, object userState) {
            if ((this.onBeginItemDeleteDelegate == null)) {
                this.onBeginItemDeleteDelegate = new BeginOperationDelegate(this.OnBeginItemDelete);
            }
            if ((this.onEndItemDeleteDelegate == null)) {
                this.onEndItemDeleteDelegate = new EndOperationDelegate(this.OnEndItemDelete);
            }
            if ((this.onItemDeleteCompletedDelegate == null)) {
                this.onItemDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginItemDeleteDelegate, new object[] {
                        cItem}, this.onEndItemDeleteDelegate, this.onItemDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemPrepare(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemPrepare(cItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool presentation.sl.services.cues.CuesSoap.EndItemPrepare(System.IAsyncResult result) {
            return base.Channel.EndItemPrepare(result);
        }
        
        private System.IAsyncResult OnBeginItemPrepare(object[] inValues, System.AsyncCallback callback, object asyncState) {
            presentation.sl.services.cues.Item cItem = ((presentation.sl.services.cues.Item)(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemPrepare(cItem, callback, asyncState);
        }
        
        private object[] OnEndItemPrepare(System.IAsyncResult result) {
            bool retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemPrepare(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemPrepareCompleted(object state) {
            if ((this.ItemPrepareCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemPrepareCompleted(this, new ItemPrepareCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemPrepareAsync(presentation.sl.services.cues.Item cItem) {
            this.ItemPrepareAsync(cItem, null);
        }
        
        public void ItemPrepareAsync(presentation.sl.services.cues.Item cItem, object userState) {
            if ((this.onBeginItemPrepareDelegate == null)) {
                this.onBeginItemPrepareDelegate = new BeginOperationDelegate(this.OnBeginItemPrepare);
            }
            if ((this.onEndItemPrepareDelegate == null)) {
                this.onEndItemPrepareDelegate = new EndOperationDelegate(this.OnEndItemPrepare);
            }
            if ((this.onItemPrepareCompletedDelegate == null)) {
                this.onItemPrepareCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemPrepareCompleted);
            }
            base.InvokeAsync(this.onBeginItemPrepareDelegate, new object[] {
                        cItem}, this.onEndItemPrepareDelegate, this.onItemPrepareCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemStart(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemStart(cItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool presentation.sl.services.cues.CuesSoap.EndItemStart(System.IAsyncResult result) {
            return base.Channel.EndItemStart(result);
        }
        
        private System.IAsyncResult OnBeginItemStart(object[] inValues, System.AsyncCallback callback, object asyncState) {
            presentation.sl.services.cues.Item cItem = ((presentation.sl.services.cues.Item)(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemStart(cItem, callback, asyncState);
        }
        
        private object[] OnEndItemStart(System.IAsyncResult result) {
            bool retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemStart(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemStartCompleted(object state) {
            if ((this.ItemStartCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemStartCompleted(this, new ItemStartCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemStartAsync(presentation.sl.services.cues.Item cItem) {
            this.ItemStartAsync(cItem, null);
        }
        
        public void ItemStartAsync(presentation.sl.services.cues.Item cItem, object userState) {
            if ((this.onBeginItemStartDelegate == null)) {
                this.onBeginItemStartDelegate = new BeginOperationDelegate(this.OnBeginItemStart);
            }
            if ((this.onEndItemStartDelegate == null)) {
                this.onEndItemStartDelegate = new EndOperationDelegate(this.OnEndItemStart);
            }
            if ((this.onItemStartCompletedDelegate == null)) {
                this.onItemStartCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemStartCompleted);
            }
            base.InvokeAsync(this.onBeginItemStartDelegate, new object[] {
                        cItem}, this.onEndItemStartDelegate, this.onItemStartCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginItemStop(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginItemStop(cItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool presentation.sl.services.cues.CuesSoap.EndItemStop(System.IAsyncResult result) {
            return base.Channel.EndItemStop(result);
        }
        
        private System.IAsyncResult OnBeginItemStop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            presentation.sl.services.cues.Item cItem = ((presentation.sl.services.cues.Item)(inValues[0]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginItemStop(cItem, callback, asyncState);
        }
        
        private object[] OnEndItemStop(System.IAsyncResult result) {
            bool retVal = ((presentation.sl.services.cues.CuesSoap)(this)).EndItemStop(result);
            return new object[] {
                    retVal};
        }
        
        private void OnItemStopCompleted(object state) {
            if ((this.ItemStopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ItemStopCompleted(this, new ItemStopCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ItemStopAsync(presentation.sl.services.cues.Item cItem) {
            this.ItemStopAsync(cItem, null);
        }
        
        public void ItemStopAsync(presentation.sl.services.cues.Item cItem, object userState) {
            if ((this.onBeginItemStopDelegate == null)) {
                this.onBeginItemStopDelegate = new BeginOperationDelegate(this.OnBeginItemStop);
            }
            if ((this.onEndItemStopDelegate == null)) {
                this.onEndItemStopDelegate = new EndOperationDelegate(this.OnEndItemStop);
            }
            if ((this.onItemStopCompletedDelegate == null)) {
                this.onItemStopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnItemStopCompleted);
            }
            base.InvokeAsync(this.onBeginItemStopDelegate, new object[] {
                        cItem}, this.onEndItemStopDelegate, this.onItemStopCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginDeviceDownStreamKeyerDisable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeviceDownStreamKeyerDisable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void presentation.sl.services.cues.CuesSoap.EndDeviceDownStreamKeyerDisable(System.IAsyncResult result) {
            base.Channel.EndDeviceDownStreamKeyerDisable(result);
        }
        
        private System.IAsyncResult OnBeginDeviceDownStreamKeyerDisable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginDeviceDownStreamKeyerDisable(callback, asyncState);
        }
        
        private object[] OnEndDeviceDownStreamKeyerDisable(System.IAsyncResult result) {
            ((presentation.sl.services.cues.CuesSoap)(this)).EndDeviceDownStreamKeyerDisable(result);
            return null;
        }
        
        private void OnDeviceDownStreamKeyerDisableCompleted(object state) {
            if ((this.DeviceDownStreamKeyerDisableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeviceDownStreamKeyerDisableCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeviceDownStreamKeyerDisableAsync() {
            this.DeviceDownStreamKeyerDisableAsync(null);
        }
        
        public void DeviceDownStreamKeyerDisableAsync(object userState) {
            if ((this.onBeginDeviceDownStreamKeyerDisableDelegate == null)) {
                this.onBeginDeviceDownStreamKeyerDisableDelegate = new BeginOperationDelegate(this.OnBeginDeviceDownStreamKeyerDisable);
            }
            if ((this.onEndDeviceDownStreamKeyerDisableDelegate == null)) {
                this.onEndDeviceDownStreamKeyerDisableDelegate = new EndOperationDelegate(this.OnEndDeviceDownStreamKeyerDisable);
            }
            if ((this.onDeviceDownStreamKeyerDisableCompletedDelegate == null)) {
                this.onDeviceDownStreamKeyerDisableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeviceDownStreamKeyerDisableCompleted);
            }
            base.InvokeAsync(this.onBeginDeviceDownStreamKeyerDisableDelegate, null, this.onEndDeviceDownStreamKeyerDisableDelegate, this.onDeviceDownStreamKeyerDisableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult presentation.sl.services.cues.CuesSoap.BeginDeviceDownStreamKeyerEnable(byte nLevel, bool bInternal, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeviceDownStreamKeyerEnable(nLevel, bInternal, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void presentation.sl.services.cues.CuesSoap.EndDeviceDownStreamKeyerEnable(System.IAsyncResult result) {
            base.Channel.EndDeviceDownStreamKeyerEnable(result);
        }
        
        private System.IAsyncResult OnBeginDeviceDownStreamKeyerEnable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte nLevel = ((byte)(inValues[0]));
            bool bInternal = ((bool)(inValues[1]));
            return ((presentation.sl.services.cues.CuesSoap)(this)).BeginDeviceDownStreamKeyerEnable(nLevel, bInternal, callback, asyncState);
        }
        
        private object[] OnEndDeviceDownStreamKeyerEnable(System.IAsyncResult result) {
            ((presentation.sl.services.cues.CuesSoap)(this)).EndDeviceDownStreamKeyerEnable(result);
            return null;
        }
        
        private void OnDeviceDownStreamKeyerEnableCompleted(object state) {
            if ((this.DeviceDownStreamKeyerEnableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeviceDownStreamKeyerEnableCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeviceDownStreamKeyerEnableAsync(byte nLevel, bool bInternal) {
            this.DeviceDownStreamKeyerEnableAsync(nLevel, bInternal, null);
        }
        
        public void DeviceDownStreamKeyerEnableAsync(byte nLevel, bool bInternal, object userState) {
            if ((this.onBeginDeviceDownStreamKeyerEnableDelegate == null)) {
                this.onBeginDeviceDownStreamKeyerEnableDelegate = new BeginOperationDelegate(this.OnBeginDeviceDownStreamKeyerEnable);
            }
            if ((this.onEndDeviceDownStreamKeyerEnableDelegate == null)) {
                this.onEndDeviceDownStreamKeyerEnableDelegate = new EndOperationDelegate(this.OnEndDeviceDownStreamKeyerEnable);
            }
            if ((this.onDeviceDownStreamKeyerEnableCompletedDelegate == null)) {
                this.onDeviceDownStreamKeyerEnableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeviceDownStreamKeyerEnableCompleted);
            }
            base.InvokeAsync(this.onBeginDeviceDownStreamKeyerEnableDelegate, new object[] {
                        nLevel,
                        bInternal}, this.onEndDeviceDownStreamKeyerEnableDelegate, this.onDeviceDownStreamKeyerEnableCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override presentation.sl.services.cues.CuesSoap CreateChannel() {
            return new CuesSoapClientChannel(this);
        }
        
        private class CuesSoapClientChannel : ChannelBase<presentation.sl.services.cues.CuesSoap>, presentation.sl.services.cues.CuesSoap {
            
            public CuesSoapClientChannel(System.ServiceModel.ClientBase<presentation.sl.services.cues.CuesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginItemCreate(string sPreset, string sFile, UserReplacement[] aUserReplacements, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = sPreset;
                _args[1] = sFile;
                _args[2] = aUserReplacements;
                System.IAsyncResult _result = base.BeginInvoke("ItemCreate", _args, callback, asyncState);
                return _result;
            }
            
            public presentation.sl.services.cues.Item EndItemCreate(System.IAsyncResult result) {
                object[] _args = new object[0];
                presentation.sl.services.cues.Item _result = ((presentation.sl.services.cues.Item)(base.EndInvoke("ItemCreate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginItemsRunningGet(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ItemsRunningGet", _args, callback, asyncState);
                return _result;
            }
            
            public Item[] EndItemsRunningGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                Item[] _result = ((Item[])(base.EndInvoke("ItemsRunningGet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInit(ulong nClientBrowserID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nClientBrowserID;
                System.IAsyncResult _result = base.BeginInvoke("Init", _args, callback, asyncState);
                return _result;
            }
            
            public string EndInit(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Init", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Ping", _args, callback, asyncState);
                return _result;
            }
            
            public void EndPing(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Ping", _args, result);
            }
            
            public System.IAsyncResult BeginItemsUpdate(Item[] aItems, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = aItems;
                System.IAsyncResult _result = base.BeginInvoke("ItemsUpdate", _args, callback, asyncState);
                return _result;
            }
            
            public Item[] EndItemsUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Item[] _result = ((Item[])(base.EndInvoke("ItemsUpdate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginItemDelete(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cItem;
                System.IAsyncResult _result = base.BeginInvoke("ItemDelete", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndItemDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ItemDelete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginItemPrepare(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cItem;
                System.IAsyncResult _result = base.BeginInvoke("ItemPrepare", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndItemPrepare(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ItemPrepare", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginItemStart(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cItem;
                System.IAsyncResult _result = base.BeginInvoke("ItemStart", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndItemStart(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ItemStart", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginItemStop(presentation.sl.services.cues.Item cItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cItem;
                System.IAsyncResult _result = base.BeginInvoke("ItemStop", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndItemStop(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ItemStop", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeviceDownStreamKeyerDisable(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DeviceDownStreamKeyerDisable", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeviceDownStreamKeyerDisable(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeviceDownStreamKeyerDisable", _args, result);
            }
            
            public System.IAsyncResult BeginDeviceDownStreamKeyerEnable(byte nLevel, bool bInternal, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = nLevel;
                _args[1] = bInternal;
                System.IAsyncResult _result = base.BeginInvoke("DeviceDownStreamKeyerEnable", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeviceDownStreamKeyerEnable(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeviceDownStreamKeyerEnable", _args, result);
            }
        }
    }
}
